name: Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install
        run: brew install typst
      - name: Build
        run: |
          typst compile CREDIT="${{ env.CREDIT }}" file.typ
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: file.pdf
          retention-days: 1
          name: Artifact